version: "3"

networks:
  my-networks:
    driver: bridge

volumes:
  dir-site:
    driver: local
    driver_opts:
      device: ${PWD}/backup
      type: none
      o: bind

services:
  my-sql:
    container_name: mysql-tap-hoa
    image: mysql:8.0
    restart: always
<<<<<<< Updated upstream

=======
    networks:
      - my-networks
>>>>>>> Stashed changes
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123abc
      MYSQL_DATABASE: taphoa-db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - "./docker/db/data:/var/lib/mysql"
      - "./docker/db/my.cnf:/etc/mysql/my.cnf"
      - "./docker/db/sql:/docker-entrypoint-initdb.d"
<<<<<<< Updated upstream
      - ${PWD}/db:/var/lib/mysql # Ánh xạ file từ máy host vào container có nghĩa là nếu sửa ở file ở máy host
=======
      - ${PWD}/db:/var/lib/mysql

  node-selenium:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-selenium
    restart: always
    depends_on:
      - my-sql
    networks:
      - my-networks
    volumes:
      - dir-site:/home/sites
    ports:
      - 8888:3003

  next-selenium:
    build:
      context: ../next-selenium
      dockerfile: Dockerfile
    container_name: nextjs
    restart: always
    networks:
      - my-networks
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 9999:3000
>>>>>>> Stashed changes
