version: "3" # chọn viết theo bản 3 docs.docker.com/compose/compose-file/

services:
  node-js:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tap-hoa-be
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    ports:
      - 3003:3003

  tap-hoa-fe:
    build:
      context: ../next-selenium
      dockerfile: Dockerfile
    container_name: tap-hoa-fe
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 9999:3000
